apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: ghost
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: ghost
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: GHOST_DATABASE_HOST
              value: mariadb
            - name: GHOST_DATABASE_NAME
              value: bitnami_ghost
            - name: GHOST_DATABASE_PORT_NUMBER
              value: "3306"
            - name: GHOST_DATABASE_USER
              value: bn_ghost
          image: docker.io/bitnami/ghost:4
          name: ghost
          ports:
            - containerPort: 2368
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/ghost
              name: bitnamighost-ghost-data
      restartPolicy: Always
      volumes:
        - name: bitnamighost-ghost-data
          persistentVolumeClaim:
            claimName: bitnamighost-ghost-data
