apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team-2
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: team-2
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MARIADB_DATABASE
              value: bitnami_ghost
            - name: MARIADB_USER
              value: bn_ghost
          image: docker.io/bitnami/mariadb:10.3
          name: mariadb
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/mariadb
              name: bitnamighost-mariadb-data
      restartPolicy: Always
      volumes:
        - name: bitnamighost-mariadb-data
          persistentVolumeClaim:
            claimName: bitnamighost-mariadb-data
